name: Build

on:
  push:
    tags:
      - v**


jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }} for ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-24.04-arm, macos-13, macos-latest, windows-latest, windows-11-arm]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - uses: actions/checkout@v4
        with:
          repository: pybind/pybind11
          ref: v3.0.1
          path: contrib/pybind11

      - uses: actions/checkout@v4
        with:
          repository: mapbox/protozero
          ref: v1.8.1
          path: contrib/protozero

      - uses: actions/checkout@v4
        with:
          repository: osmcode/libosmium
          ref: v2.22.0
          path: contrib/libosmium

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==3.1.4

      - name: Build wheels
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        shell: bash
        env:
           CIBW_ENABLE: cpython-freethreading
           CIBW_ARCHS: "native"
           CIBW_SKIP: "*musllinux* *cp313t-win* *cp314t-win*"
           CIBW_TEST_REQUIRES: pytest pytest-httpserver
           CIBW_TEST_COMMAND: pytest {project}/test
           CIBW_BUILD_FRONTEND: build
           CIBW_BEFORE_BUILD_LINUX: yum install -y expat-devel boost-devel zlib-devel bzip2-devel lz4-devel
           CIBW_BEFORE_BUILD_MACOS: brew install boost
           CIBW_BEFORE_BUILD_WINDOWS: vcpkg install bzip2 expat zlib boost-variant boost-iterator lz4
           CIBW_ENVIRONMENT_WINDOWS: CMAKE_TOOLCHAIN_FILE="C:/vcpkg/scripts/buildsystems/vcpkg.cmake" Python_ROOT_DIR= Python3_ROOT_DIR=
           CIBW_ENVIRONMENT_MACOS: CMAKE_WITH_LZ4=OFF MACOSX_DEPLOYMENT_TARGET=11.0 Python_ROOT_DIR= Python3_ROOT_DIR=
           CIBW_REPAIR_WHEEL_COMMAND_MACOS: ""

      - uses: actions/upload-artifact@v4
        with:
          name: pyosmium-wheels-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl
